services:
  webapi_one:
    image: ursu/hangfire-demo:latest
    build:
      context: VHD
      dockerfile: Dockerfile
    ports:
      - "6061:8080"
    environment:
      ServiceOptions__ServiceName: "Docker One"
      ServiceOptions__HangfireConnection: "Host=postgres; Database=postgres; Username=postgres; Password=postgres"
      ServiceOptions__HangfireQueues: "one,default"
  
  webapi_two:
    image: ursu/hangfire-demo:latest
    build:
      context: VHD
      dockerfile: Dockerfile
    ports:
      - "6062:8080"
    environment:
      ServiceOptions__ServiceName: "Docker Two"
      ServiceOptions__HangfireConnection: "Host=postgres; Database=postgres; Username=postgres; Password=postgres"
      ServiceOptions__HangfireQueues: "two,default"

  postgres:
    image: postgres:15.7-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
