services:

  webapi_one:
    image: ursu/webapi-hangfire:latest
    build:
      context: VHD
      dockerfile: WebApi/Dockerfile
    ports:
      - "6061:8080"
    env_file:
      - .env
    environment:
      ServiceOptions__ServiceName: "One"
    depends_on:
      - postgres

  webapi_two:
    image: ursu/webapi-hangfire:latest
    build:
      context: VHD
      dockerfile: WebApi/Dockerfile
    ports:
      - "6062:8080"
    env_file:
      - .env
    environment:
      ServiceOptions__ServiceName: "Two"
    depends_on:
      - postgres

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888" # UI
      - "4317:18889" # gRPC

  postgres:
    image: postgres:15.7-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
