name: vhd

services:

  one:
    image: ursu/vhdapi:latest
    build:
      context: VHD
      dockerfile: WebApi/Dockerfile
    ports:
      - "6061:8080"
    env_file:
      - .env
    environment:
      ServiceOptions__ServiceName: "One"
    depends_on:
      - postgres

  two:
    image: ursu/vhdapi:latest
    build:
      context: VHD
      dockerfile: WebApi/Dockerfile
    ports:
      - "6062:8080"
    env_file:
      - .env
    environment:
      ServiceOptions__ServiceName: "Two"
    depends_on:
      - postgres

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - "18888:18888" # UI
      - "18889:18889" # gRPC

  postgres:
    image: postgres:15.7-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  master:
    image: cribl/cribl:latest
    environment:
      - CRIBL_DIST_MODE=master
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
      - "19000:9000"
    volumes:
      - "./config/cribl/cribl-config:/opt/cribl/config-volume"

  worker:
    image: cribl/cribl:latest
    depends_on: 
      - master
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@master:4200
    ports:
      - "9000:9000"
      - "4317:4317"
